version: '2'

services:
  mysql:
    image: wantmys2000/mysql-tiny
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
  website:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - dropwizard
    ports:
      - '80:80'
    volumes:
      - './angular/app:/usr/share/nginx/html:ro'
  angular:
    image: nhoag/angularjs
    volumes:
      - './angular:/app'
    tty:
      true
  dropwizard:
    image: mondary/dropwizard
    links:
      - mysql
    ports:
      - '8080:8080'
      - '9080:9080'
    volumes:
      - './dropwizard:/opt/service'
    tty:
      true
