version: '2'

services:
  mysql:
    image: wantmys2000/mysql-tiny
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
  dropwizard:
    build:
      context: .
      dockerfile: Dockerfile.dropwizard
    links:
      - mysql
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - './middle_tier/app'
  website:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - dropwizard
    ports:
      - '80:80'
    volumes:
      - './angular:app'
