FROM maven:3.3.9-jdk-8

MAINTAINER c.jekal "charles.jekal@cgi.com"

EXPOSE 8080
EXPOSE 8081
EXPOSE 2003

WORKDIR /usr/src/app

COPY dropwizard/pom.xml .
RUN mvn verify clean --fail-never
COPY dropwizard/ .

CMD ["/bin/bash"]
