version: '2'

services:
  mysql:
    image: wantmys2000/mysql-tiny
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
  website:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
      - '80:80'
    volumes:
      - './angular:/usr/share/nginx/html:ro'
  angular:
    image: nhoag/angularjs
    volumes:
      - './angular:/app'
