version: '2'

services:
  mysql:
    image: wantmys2000/mysql-tiny
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
  website:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - dropwizard
    ports:
      - '80:80'
    volumes:
      - './angular/app:/usr/share/nginx/html:ro'
  angular:
    image: nhoag/angularjs
    volumes:
      - './angular:/app'
    tty:
      true
  dropwizard:
    build:
      context: .
      dockerfile: Dockerfile.dropwizard
    links:
      - mysql
    ports:
      - '8080:8080'
      - '8081:8081'
      - '2003:2003'
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - './dropwizard:/usr/src/app'
    tty:
      true
